/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.restaurante;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Carla
 */
public class Restaurante extends javax.swing.JFrame {

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }
    
    Color greenPerso = new Color(102,255,102);
    Color redPerso = new Color(255,51,51);

    int mesa1 = 0;
    int mesa2 = 0;
    int mesa3 = 0;
    int mesa4 = 0;
    int mesa5 = 0;
    int mesa6 = 0;
    int mesa7 = 0;
    int mesa8 = 0;
    int mesa9 = 0;
    int mesa10 = 0;
    int mesa11 = 0;
    int mesa12 = 0;
    int totalClientes = 0;
    int clientesMesa = 0;
    int clientesBarra = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMesa1 = new javax.swing.JLabel();
        jLabelMesa2 = new javax.swing.JLabel();
        jLabelMesa3 = new javax.swing.JLabel();
        jLabelMesa4 = new javax.swing.JLabel();
        jLabelMesa5 = new javax.swing.JLabel();
        jLabelMesa6 = new javax.swing.JLabel();
        jLabelMesa7 = new javax.swing.JLabel();
        jLabelMesa8 = new javax.swing.JLabel();
        jLabelMesa9 = new javax.swing.JLabel();
        jLabelMesa10 = new javax.swing.JLabel();
        jLabelMesa11 = new javax.swing.JLabel();
        jLabelMesa12 = new javax.swing.JLabel();
        jComboBoxCapacidad1 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad2 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad3 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad4 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad5 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad6 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad7 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad8 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad9 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad10 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad11 = new javax.swing.JComboBox<>();
        jComboBoxCapacidad12 = new javax.swing.JComboBox<>();
        jLabelTotalClientes = new javax.swing.JLabel();
        jLabelEnMesa = new javax.swing.JLabel();
        jLabelEnBarra = new javax.swing.JLabel();
        jLabelBarra = new javax.swing.JLabel();
        jToggleButtonBarra1 = new javax.swing.JToggleButton();
        jToggleButtonBarra2 = new javax.swing.JToggleButton();
        jToggleButtonBarra3 = new javax.swing.JToggleButton();
        jToggleButtonBarra4 = new javax.swing.JToggleButton();
        jToggleButtonBarra5 = new javax.swing.JToggleButton();
        jToggleButtonBarra6 = new javax.swing.JToggleButton();
        jToggleButtonBarra7 = new javax.swing.JToggleButton();
        jToggleButtonBarra8 = new javax.swing.JToggleButton();
        jToggleButtonBarra9 = new javax.swing.JToggleButton();
        jToggleButtonBarra10 = new javax.swing.JToggleButton();
        jToggleButtonBarra11 = new javax.swing.JToggleButton();
        jToggleButtonBarra12 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa1.setText("Mesa 1");
        jLabelMesa1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa2.setText("Mesa 2");
        jLabelMesa2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa3.setText("Mesa 3");
        jLabelMesa3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa4.setText("Mesa 4");
        jLabelMesa4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa5.setText("Mesa 5");
        jLabelMesa5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa6.setText("Mesa 6");
        jLabelMesa6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa7.setText("Mesa 7");
        jLabelMesa7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa8.setText("Mesa 8");
        jLabelMesa8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa9.setText("Mesa 9");
        jLabelMesa9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa10.setText("Mesa 10");
        jLabelMesa10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa11.setText("Mesa 11");
        jLabelMesa11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMesa12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa12.setText("Mesa 12");
        jLabelMesa12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxCapacidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        jComboBoxCapacidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad1ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));
        jComboBoxCapacidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad2ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad3ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad4ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad5ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad6ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad7ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBoxCapacidad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad8ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCapacidad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad9ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCapacidad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad10ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCapacidad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad11ActionPerformed(evt);
            }
        });

        jComboBoxCapacidad12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxCapacidad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCapacidad12ActionPerformed(evt);
            }
        });

        jLabelTotalClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTotalClientes.setText("Total clientes: 0/60");

        jLabelEnMesa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEnMesa.setText("En mesa: 0/54");

        jLabelEnBarra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelEnBarra.setText("En barra: 0/12");

        jLabelBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBarra.setText("Barra 0/12");
        jLabelBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToggleButtonBarra1.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra1ActionPerformed(evt);
            }
        });

        jToggleButtonBarra2.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra2ActionPerformed(evt);
            }
        });

        jToggleButtonBarra3.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra3ActionPerformed(evt);
            }
        });

        jToggleButtonBarra4.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra4ActionPerformed(evt);
            }
        });

        jToggleButtonBarra5.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra5ActionPerformed(evt);
            }
        });

        jToggleButtonBarra6.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra6ActionPerformed(evt);
            }
        });

        jToggleButtonBarra7.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra7ActionPerformed(evt);
            }
        });

        jToggleButtonBarra8.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra8ActionPerformed(evt);
            }
        });

        jToggleButtonBarra9.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra9ActionPerformed(evt);
            }
        });

        jToggleButtonBarra10.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra10ActionPerformed(evt);
            }
        });

        jToggleButtonBarra11.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra11ActionPerformed(evt);
            }
        });

        jToggleButtonBarra12.setBackground(new java.awt.Color(102, 255, 102));
        jToggleButtonBarra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBarra12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEnBarra)
                            .addComponent(jLabelEnMesa)
                            .addComponent(jLabelTotalClientes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxCapacidad9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCapacidad10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxCapacidad11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCapacidad12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCapacidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxCapacidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxCapacidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCapacidad3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCapacidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCapacidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCapacidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMesa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonBarra12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelTotalClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEnMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEnBarra)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCapacidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCapacidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCapacidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCapacidad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCapacidad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCapacidad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBoxCapacidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxCapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCapacidad9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCapacidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMesa11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCapacidad11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxCapacidad12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButtonBarra7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButtonBarra2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonBarra6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCapacidad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad9ActionPerformed
        mesa9 = Integer.parseInt(jComboBoxCapacidad9.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad9.setSelectedIndex(0);
            mesa9 = Integer.parseInt(jComboBoxCapacidad9.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
        
    }//GEN-LAST:event_jComboBoxCapacidad9ActionPerformed

    private void jComboBoxCapacidad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad10ActionPerformed
        mesa10 = Integer.parseInt(jComboBoxCapacidad10.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad10.setSelectedIndex(0);
            mesa10 = Integer.parseInt(jComboBoxCapacidad10.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad10ActionPerformed

    private void jComboBoxCapacidad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad11ActionPerformed
        mesa11 = Integer.parseInt(jComboBoxCapacidad11.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad11.setSelectedIndex(0);
            mesa11 = Integer.parseInt(jComboBoxCapacidad11.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad11ActionPerformed

    private void jComboBoxCapacidad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad12ActionPerformed
        mesa12 = Integer.parseInt(jComboBoxCapacidad12.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad12.setSelectedIndex(0);
            mesa12 = Integer.parseInt(jComboBoxCapacidad12.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad12ActionPerformed

    private void jComboBoxCapacidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad1ActionPerformed
        mesa1 = Integer.parseInt(jComboBoxCapacidad1.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad1.setSelectedIndex(0);
            mesa1 = Integer.parseInt(jComboBoxCapacidad1.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad1ActionPerformed

    private void jComboBoxCapacidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad2ActionPerformed
        mesa2 = Integer.parseInt(jComboBoxCapacidad2.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad2.setSelectedIndex(0);
            mesa2 = Integer.parseInt(jComboBoxCapacidad2.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad2ActionPerformed

    private void jComboBoxCapacidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad3ActionPerformed
        mesa3 = Integer.parseInt(jComboBoxCapacidad3.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad3.setSelectedIndex(0);
            mesa3 = Integer.parseInt(jComboBoxCapacidad3.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad3ActionPerformed

    private void jComboBoxCapacidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad4ActionPerformed
        mesa4 = Integer.parseInt(jComboBoxCapacidad4.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad4.setSelectedIndex(0);
            mesa4 = Integer.parseInt(jComboBoxCapacidad4.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad4ActionPerformed

    private void jComboBoxCapacidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad5ActionPerformed
        mesa5 = Integer.parseInt(jComboBoxCapacidad5.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad5.setSelectedIndex(0);
            mesa5 = Integer.parseInt(jComboBoxCapacidad5.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad5ActionPerformed

    private void jComboBoxCapacidad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad6ActionPerformed
        mesa6 = Integer.parseInt(jComboBoxCapacidad6.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad6.setSelectedIndex(0);
            mesa6 = Integer.parseInt(jComboBoxCapacidad6.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad6ActionPerformed

    private void jComboBoxCapacidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad7ActionPerformed
        mesa7 = Integer.parseInt(jComboBoxCapacidad7.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad7.setSelectedIndex(0);
            mesa7 = Integer.parseInt(jComboBoxCapacidad7.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad7ActionPerformed

    private void jComboBoxCapacidad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCapacidad8ActionPerformed
        mesa8 = Integer.parseInt(jComboBoxCapacidad8.getSelectedItem().toString());
        totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
        clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
        if (clientesMesa <= 54 && totalClientes <= 60) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        } else {
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo en mesa/establecimiento.");
            jComboBoxCapacidad8.setSelectedIndex(0);
            mesa8 = Integer.parseInt(jComboBoxCapacidad8.getSelectedItem().toString());
            totalClientes = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12 + clientesBarra;
            clientesMesa = mesa1 + mesa2 + mesa3 + mesa4 + mesa5 + mesa6 + mesa7 + mesa8 + mesa9 + mesa10 + mesa11 + mesa12;
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnMesa.setText("En mesa: " + clientesMesa + "/54");
        }
    }//GEN-LAST:event_jComboBoxCapacidad8ActionPerformed

    private void jToggleButtonBarra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra2ActionPerformed
        if (jToggleButtonBarra2.isSelected()) {
            jToggleButtonBarra2.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra2.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra2ActionPerformed

    private void jToggleButtonBarra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra1ActionPerformed
        if (jToggleButtonBarra1.isSelected()) {
            jToggleButtonBarra1.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
            
        } else {
            jToggleButtonBarra1.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra1ActionPerformed

    private void jToggleButtonBarra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra3ActionPerformed
        if (jToggleButtonBarra3.isSelected()) {
            jToggleButtonBarra3.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra3.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }    
    }//GEN-LAST:event_jToggleButtonBarra3ActionPerformed

    private void jToggleButtonBarra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra4ActionPerformed
        if (jToggleButtonBarra4.isSelected()) {
            jToggleButtonBarra4.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra4.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra4ActionPerformed

    private void jToggleButtonBarra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra5ActionPerformed
        if (jToggleButtonBarra5.isSelected()) {
            jToggleButtonBarra5.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra5.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra5ActionPerformed

    private void jToggleButtonBarra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra6ActionPerformed
        if (jToggleButtonBarra6.isSelected()) {
            jToggleButtonBarra6.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra6.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra6ActionPerformed

    private void jToggleButtonBarra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra7ActionPerformed
        if (jToggleButtonBarra7.isSelected()) {
            jToggleButtonBarra7.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra7.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra7ActionPerformed

    private void jToggleButtonBarra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra8ActionPerformed
        if (jToggleButtonBarra8.isSelected()) {
            jToggleButtonBarra8.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra8.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra8ActionPerformed

    private void jToggleButtonBarra9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra9ActionPerformed
        if (jToggleButtonBarra9.isSelected()) {
            jToggleButtonBarra9.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra9.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra9ActionPerformed

    private void jToggleButtonBarra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra10ActionPerformed
        if (jToggleButtonBarra10.isSelected()) {
            jToggleButtonBarra10.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra10.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra10ActionPerformed

    private void jToggleButtonBarra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra11ActionPerformed
        if (jToggleButtonBarra11.isSelected()) {
            jToggleButtonBarra11.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra11.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra11ActionPerformed

    private void jToggleButtonBarra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBarra12ActionPerformed
        if (jToggleButtonBarra12.isSelected()) {
            jToggleButtonBarra12.setBackground(redPerso);
            totalClientes++;
            clientesBarra++;
        } else {
            jToggleButtonBarra12.setBackground(greenPerso);
            totalClientes--;
            clientesBarra--;
        }
        if (totalClientes <= 60 && clientesBarra <=12) {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        } else {
            jLabelTotalClientes.setText("Total clientes: " + totalClientes + "/60");
            jLabelEnBarra.setText("En barra: " + clientesBarra + "/12");
        }
    }//GEN-LAST:event_jToggleButtonBarra12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCapacidad1;
    private javax.swing.JComboBox<String> jComboBoxCapacidad10;
    private javax.swing.JComboBox<String> jComboBoxCapacidad11;
    private javax.swing.JComboBox<String> jComboBoxCapacidad12;
    private javax.swing.JComboBox<String> jComboBoxCapacidad2;
    private javax.swing.JComboBox<String> jComboBoxCapacidad3;
    private javax.swing.JComboBox<String> jComboBoxCapacidad4;
    private javax.swing.JComboBox<String> jComboBoxCapacidad5;
    private javax.swing.JComboBox<String> jComboBoxCapacidad6;
    private javax.swing.JComboBox<String> jComboBoxCapacidad7;
    private javax.swing.JComboBox<String> jComboBoxCapacidad8;
    private javax.swing.JComboBox<String> jComboBoxCapacidad9;
    private javax.swing.JLabel jLabelBarra;
    private javax.swing.JLabel jLabelEnBarra;
    private javax.swing.JLabel jLabelEnMesa;
    private javax.swing.JLabel jLabelMesa1;
    private javax.swing.JLabel jLabelMesa10;
    private javax.swing.JLabel jLabelMesa11;
    private javax.swing.JLabel jLabelMesa12;
    private javax.swing.JLabel jLabelMesa2;
    private javax.swing.JLabel jLabelMesa3;
    private javax.swing.JLabel jLabelMesa4;
    private javax.swing.JLabel jLabelMesa5;
    private javax.swing.JLabel jLabelMesa6;
    private javax.swing.JLabel jLabelMesa7;
    private javax.swing.JLabel jLabelMesa8;
    private javax.swing.JLabel jLabelMesa9;
    private javax.swing.JLabel jLabelTotalClientes;
    private javax.swing.JToggleButton jToggleButtonBarra1;
    private javax.swing.JToggleButton jToggleButtonBarra10;
    private javax.swing.JToggleButton jToggleButtonBarra11;
    private javax.swing.JToggleButton jToggleButtonBarra12;
    private javax.swing.JToggleButton jToggleButtonBarra2;
    private javax.swing.JToggleButton jToggleButtonBarra3;
    private javax.swing.JToggleButton jToggleButtonBarra4;
    private javax.swing.JToggleButton jToggleButtonBarra5;
    private javax.swing.JToggleButton jToggleButtonBarra6;
    private javax.swing.JToggleButton jToggleButtonBarra7;
    private javax.swing.JToggleButton jToggleButtonBarra8;
    private javax.swing.JToggleButton jToggleButtonBarra9;
    // End of variables declaration//GEN-END:variables
}
